Locales['de'] = {
    --Community Service Translates
    jailchoreblip = 'Gefängnisarbeit',
    communityseviceblip = 'Gemeinschaftsdienst',
    presstodotask = "Drücken Sie 'E', um die Aufgabe zu starten ",
    choosechore = 'Wähle Arbeit: ',
    amountofchores = 'Anzahl der Aufgaben: ',
    giveservice = 'Dienst erteilen',
    servicemenu = 'Menü Gemeinschaftsdienst',
    choretype = 'Bauwesen',
    --Input Translates
    inputconfirm = 'Bestätigen',
    playerid = 'Player ID: ',
    fineamount = 'Geldstrafe: ',
    jailamount = 'Haftstrafe: ',
    numberonly = 'Nur Nummern',
    --Menu Translates
    lawmenu = 'Gesetz Menü',
    searchplayer = 'Bürger durchsuchen',
    togglebadge = 'Abzeichen wechseln',
    cufftoggle = 'Bürger fesseln/entfesseln',
    escort = 'Begleite Spieler in Handschellen',
    fineplayer = 'Geldstrafe',
    jailplayer = 'Bürger einsperren',
    serviceplayer = 'Gemeinschaftsdienst zuweisen',
    grabammo = "Munition abnehmen",
    grabweapons = "Waffen abnehmen",
    Cabinet = "Schrank",
    putinoutvehicle = 'In die Kutsche setzen/aus der Kutsche holen',
    inventorytitle = "Bürger Inventar",
    --Fine Menu Translates
    bill = "Rechnung (Syn_Society)",
    billdesc = 'Bürger eine Rechnung geben, die er später bezahlen kann',
    fine = 'Geldstrafe (regulär)',
    finedesc = 'Dem Bürger eine Geldstrafe geben, diese wird direkt abgenommen',
    --ID Menu Translates
    idmenu = 'ID Menu',
    citizenid = "Bürger ID",
    horseowner = "Besitzer des Pferdes ermitteln",
    horseownerdesc = "Ermittelt den Besitzer des Pferdes, wenn der Besitzer nicht in der Nähe ist, wird kein Besitzer angezeigt",
    --Search Menu Translates
    searchmenu = 'Durchsuchen Menü',
    playermoney = 'Geld: ',
    checkitems = 'Items prüfen',
    checkweapons = 'Waffen prüfen',
    --Jail Menu Translates
    Autotele = "Auto Tele: ",
    Autoteledesc = "Soll der Bürger mitgenommen oder manuell transportiert werden?",
    jaillocaiton = "Ort des Gefängnisses: ",
    jail = "Bürger einsperren",
    jaildesc = 'Wenn "Auto Jail" false ist, müssen Sie den Bürger transportieren, andernfalls werden es die Einheimischen tun.',
    unjail = "Bürger aus dem Gefängniss holen, ID oben",
    jailmenu = "Gefägniss Menü",
    --Jail Locations
    valjail = "Valentine Büro des Sheriffs",
    bwjail = "Blackwater Büro des Sheriffs",
    tujail = "Tumbleweed Büro des Sheriffs",
    stjail = "Strawberry Büro des Sheriffs",
    sdjail = "Saint Denis Büro des Sheriffs",
    anjail = "Annesburg Büro des Sheriffs",
    arjail = "Armadillo Büro des Sheriffs",
    rhjail = 'Rhodes Büro des Sheriffs',
    sisika = 'Sisika Gefägniss',
    --Notify Translates
    badgeon = 'Sie setzen Ihre Marke auf',
    badgeoff = 'Sie nehmen Ihre Marke ab',
    notcloseenough = 'Nicht nah genug an einem Bürger',
    notcloseenoughtowagon = 'Nicht nah genug an einer Kutsche',
    jailbreak = 'Du bist aus dem Gefängnis ausgebrochen. Jetzt lauf!',
    onduty = 'Sie sind bereits im Dienst',
    imprisoned = 'Sie sind inhaftiert für: ',
    minutes = ' Minuten',
    jailseconds = ' verbleibende Sekunden',
    released = "Du bist aus dem Gefängnis entlassen worden, schön anständig bleiben!",
    youhave = "Du hast ",
    secondsremaining = ' Sekunden Zeit zur Rückkehr, bevor du ins Gefängnis kommst',
    crimereported = 'Verbrechen gemeldet',
    jailbreakalert = "Es wurde ein Gefängnisausbruch gemeldet, gucken Sie auf Ihrer Karte nach dem Ort",
    goonduty = 'Sie sind jetzt im Dienst',
    nottherightjob = "Sie haben nicht den richtigen Job",
    gooffduty = 'Sie sind jetzt außer Dienst',
    youfined = 'Sie haben eine Geldstrafe ',
    currency = '$',
    recievedfine = 'Du bekommst eine Geldstrafe von $',
    givenservice = 'Sie haben gemeinnützige Arbeit geleistet',
    idcheck = 'ID überprüfen',
    name = 'Name: ',
    job = 'Job: ',
    notowned = "Das Pferd besitz keiner",
    taskfailed = 'Aufgabe fehlgeschlagen',
    servicecomplete = 'Gemeinnützige Arbeit abgeschlossen!',
    lockpickbroke = "Verflixt und zugenäht! Mein Dietrich ist gebrochen",
    jailed = "Du wurdest wegen Verstoßes gegen den Zivildienst inhaftiert, reiß dich zusammen",
    outofroom = "Sie haben keinen Platz mehr",
    notcuffed = "Bürger ist nicht gefesselt",
    --Webhook Translates
    sentto = ' sent ',
    tojailfor = ' to jail for ',
    seconds = ' seconds ',
    gaveservice = ' gave ',
    ofchores = ' chores ',
    unjailed = ' unjailed ',
    gaveafine = ' gave a fine of $',
    to = ' to ',
    took = ' took ',
    of = ' of ',
    from = ' from ',
    --Misc Translates
    none = 'None',
    varfalse = 'falsch',
    vartrue = 'wahr',
    opencabinet = 'Schrank öffnen',
    search = 'Durchsuchen',
    invalid = ' invalid ',
    --Badge Translates
    up = "Marke nach oben",
    left = "Marke nach links",
    right = "Marke nach rechts",
    down = "Marke nach unten",
    sisika_commisary = 'Drücke "G", um Essen und Wasser zu erhalten.',
    youarenotonduty ='Sie sind nicht im Dienst',
    nocuffs = 'Sie haben keine Handschellen'
}
