Locales['ro'] = {
    --Traduceri Serviciu Comunitar
    jailchoreblip = 'Corvoada inchisoare',
    communityseviceblip = 'Serviciu comunitar',
    presstodotask = "Apasa 'E' pentru a incepe sarcina ",
    choosechore = 'Alege corvoada: ',
    amountofchores = 'Numar de corvoade: ',
    giveservice = 'Ofera Serviciu',
    servicemenu = 'Meniu Serviciu Comunitar',
    choretype = 'Constructie',
    --Traduceri Intrare
    inputconfirm = 'Confirma',
    playerid = 'ID Jucator: ',
    fineamount = 'Suma amenzii: ',
    jailamount = 'Timp inchisoare: ',
    numberonly = 'Numai numere',
    --Traduceri Meniu
    lawmenu = 'Meniu Legislativ',
    searchplayer = 'Cauta Cetatean',
    togglebadge = 'Arata/Ascunde Insigna',
    cufftoggle = 'Catuseaza/Decatuseaza Cetatean',
    escort = 'Escoreaza Jucator Algesit',
    fineplayer = 'Amenzi Cetatean',
    jailplayer = 'Inchide Jucator',
    serviceplayer = 'Atribuie Serviciu Comunitar',
    grabammo = "Ia Munitie",
    grabweapons = "Ia Arme",
    Cabinet = "Dulap",
    putinoutvehicle = 'Pune/ Scoate din vehicul',
    inventorytitle = "Traista Cetateanului",
    --Traduceri Meniu Amenda
    bill = "Factura (Sin_Society)",
    billdesc = 'Factureaza Cetateanul, permitandu-i sa plateasca mai tarziu, catre societate',
    fine = 'Amenda (Regulara)',
    finedesc = 'Amendeaza Cetateanul, ia banii pe loc de la cetatean, catre societate',
    --Traduceri Meniu ID
    idmenu = 'Meniu ID',
    citizenid = "Obtine ID-ul Cetateanului",
    horseowner = "Obtine Proprietarul Calului",
    horseownerdesc = "Obtine Proprietarul Calului, Daca proprietarul nu este in apropiere, va reveni fara proprietar",
    --Traduceri Meniu Cautare
    searchmenu = 'Meniu Cautare',
    playermoney = 'Bani: ',
    checkitems = 'Verifica Obiecte',
    checkweapons = 'Verifica Arme',
    --Traduceri Meniu Inchisoare
    Autotele = "Teleport Automat: ",
    Autoteledesc = "Daca Cetateanul trebuie dus automat sau transportat manual",
    jaillocaiton = "Locatie Inchisoare: ",
    jail = "Inchide Cetatean",
    jaildesc = 'Daca Inchisoare Automata este falsa atunci trebuie sa transporti Cetateanul daca nu localnicii vor face asta',
    unjail = "Elibereaza Cetateanul ID de mai sus",
    jailmenu = "Meniu Inchisoare",
    --Locatii Inchisoare
    valjail = "Birou Serif Valentine",
    bwjail = "Birou Serif Blackwater",
    tujail = "Birou Serif Tumbleweed",
    stjail = "Birou Serif Strawberry",
    sdjail = "Birou Serif Saint Denis",
    anjail = "Birou Serif Annesburg",
    arjail = "Birou Serif Armadillo",
    rhjail = 'Birou Serif Rhodes',
    sisika = 'Inchisoarea Sisika',
    --Traduceri Notificari
    badgeon = 'Ti-ai pus insigna',
    badgeoff = 'Ti-ai dat jos insigna',
    notcloseenough = 'Nu esti suficient de aproape de un cetatean',
   

 notcloseenoughtowagon = 'Nu esti suficient de aproape de un vehicul',
    jailbreak = 'Ai fost eliberat din inchisoare. Acum fugi!',
    onduty = 'Esti deja in serviciu',
    imprisoned = 'Esti inchis pentru: ',
    minutes = ' minute',
    jailseconds = ' secunde ramase',
    released = "Ai fost eliberat din inchisoare. Acum comporta-te cum trebuie!",
    youhave = "Ai ",
    secondsremaining = ' secunde ramase sa te intorci inainte de a fi inchis',
    crimereported = 'Crima raportata',
    jailbreakalert = "O evadare din inchisoare a fost raportata, verifica harta pentru locatie",
    goonduty = 'Acum esti in serviciu',
    nottherightjob = "Nu ai slujba potrivita",
    gooffduty = 'Acum nu mai esti in serviciu',
    youfined = 'Ai amendat ',
    currency = 'lei',
    recievedfine = 'Ai primit o amenda de lei',
    givenservice = 'Ti-a fost atribuit Serviciu Comunitar',
    idcheck = 'Verificare ID',
    name = 'Nume: ',
    job = 'Slujba: ',
    notowned = "Calul nu are proprietar",
    taskfailed = 'Sarcina esuata',
    servicecomplete = 'Serviciu Comunitar Completat, comporta-te cum trebuie!',
    lockpickbroke = "Blestem! Mi s-a rupt scula de deschis lacate!",
    jailed = "Ai fost inchis pentru ca ai incalcat Serviciul Comunitar, comporta-te cum trebuie",
    outofroom = "Nu ai suficient spatiu",
    notcuffed = "Cetateanul nu este incatusat",
    --Traduceri Webhook
    sentto = ' a trimis ',
    tojailfor = ' la inchisoare pentru ',
    seconds = ' secunde ',
    gaveservice = ' a dat ',
    ofchores = ' corvoade ',
    unjailed = ' eliberat ',
    gaveafine = ' a dat o amenda de lei',
    to = ' catre ',
    took = ' a luat ',
    of = ' de ',
    from = ' de la ',
    --Traduceri Diverse
    none = 'Niciunul',
    varfalse = 'fals',
    vartrue = 'adevarat',
    opencabinet = 'Deschide Dulapul',
    search = 'Cauta',
    invalid = ' invalid ',
    --Traduceri Insigna
    up = "Muta Insigna Sus",
    left = "Muta Insigna Stanga",
    right = "Muta Insigna Dreapta",
    down = "Muta Insigna Jos",
    sisika_commisary = 'Apasa "G" pentru a lua mancare si apa.',
    youarenotonduty ='nu esti in serviciu',
    nocuffs = 'nu ai catuse'
}
